remote_theme: jekyll/minima@10124515953527c8990a2de99ae4ddb2a81ffee3

title: First Dawn LLC
description: Documentation and support for First Dawn LLC's Atlassian Marketplace apps.
author:
  name: First Dawn LLC
  email: support@firstdawnllc.atlassian.net

header_pages:
  - pinned-comments-faq.md
  - lens-group-debugger-faq.md
  - issue-star-faq.md
  - comment-to-issue-faq.md

plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
